
export const FETCH_CATEGORIES = 'FETCHING_CATEGORIES';
export const FETCHED_CATEGORIES = 'FETCHED_CATEGORIES';
export const FETCHED_CATEGORIES_ERROR = 'FETCHED_CATEGORIES_ERROR';
export const FETCH_CATEGORY = 'FETCHING_CATEGORY';
export const FETCHED_CATEGORY = 'FETCHED_CATEGORY';
export const FETCHED_CATEGORY_ERROR = 'FETCHED_CATEGORY_ERROR';
export const CREATE_CATEGORY = 'ADDING_CATEGORY';
export const CREATED_CATEGORY = 'ADDED_CATEGORY';
export const CREATED_CATEGORY_ERROR = 'ADDED_CATEGORY_ERROR';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATED_CATEGORY = 'UPDATED_CATEGORY';
export const UPDATED_CATEGORY_ERROR = 'UPDATED_CATEGORY_ERROR';
export const DESTROY_CATEGORY = 'DESTROY_CATEGORY';
export const DESTROYED_CATEGORY = 'DESTROYED_CATEGORY';
export const DESTROYED_CATEGORY_ERROR = 'DESTROYED_CATEGORY_ERROR';